Models/AddJournalViewModel.cs
namespace JourJournal.Models
{
    public class AddJournalViewModel
    {
        public string title { get; set; }
        public string description { get; set; }
    }
}

Models/Journal.cs
namespace JourJournal.Models
{
    public class Journal
    {
        public Guid Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    }
}

Models/UpdateJournalViewModel.cs
namespace JourJournal.Models
{
    public class UpdateJournalViewModel
    {
        public Guid Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    }
}

Controllers/JournalController.cs
using JourJournal.Data;
using JourJournal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace JourJournal.Controllers
{
    public class JournalController : Controller
    {
        private readonly JourJournalDbContext jourJournalDbContext;
        public JournalController(JourJournalDbContext jourJournalDbContext)
        {
            this.jourJournalDbContext = jourJournalDbContext;
        }

        // Display Journal List
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var journal = await jourJournalDbContext.JournalList.ToListAsync();
            return View(journal);
        }

        // Display Add Form
        [HttpGet]
        public IActionResult AddJournal()
        {
            return View();
        }

        // Adding Journal
        [HttpPost]
        public async Task<IActionResult> AddJournal(AddJournalViewModel addJournal)
        {
            var journal = new Journal()
            {
                Id = Guid.NewGuid(),
                title = addJournal.title,
                description = addJournal.description
            };
            await jourJournalDbContext.JournalList.AddAsync(journal);
            await jourJournalDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // Updating Journal - Display Form
        [HttpGet]
        public async Task<IActionResult> UpdateJournal(Guid Id)
        {
            var journal = await jourJournalDbContext.JournalList.FirstOrDefaultAsync(x => x.Id == Id);
            if (journal != null)
            {
                var updateModel = new UpdateJournalViewModel()
                {
                    Id = journal.Id,
                    title = journal.title,
                    description = journal.description
                };
                return await Task.Run(() => View("UpdateJournal", updateModel));
            }
            return RedirectToAction("Index");
        }

        // Updating Journal Data
        [HttpPost]
        public async Task<IActionResult> UpdateJournal(UpdateJournalViewModel model)
        {
            var journal = await jourJournalDbContext.JournalList.FindAsync(model.Id);
            if (journal != null)
            {
                journal.title = model.title;
                journal.description = model.description;

                await jourJournalDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // Deleting Journal
        [HttpPost]
        public async Task<IActionResult> DeleteJournal(UpdateJournalViewModel model)
        {
            var journal = await jourJournalDbContext.JournalList.FindAsync(model.Id);
            if (journal != null)
            {
                jourJournalDbContext.JournalList.Remove(journal);
                await jourJournalDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Journal/AddJournal.cshtml
@model JourJournal.Models.AddJournalViewModel;

<div class="container w-50 my-5">
    <div class="text-center mb-5">
    <h1 class="display-4 fw-semibold my-3"><a asp-controller="Journal" asp-action="Index">My Journal</a></h1>
    </div>
      <form method="post" action="AddJournal">
         <div class="mb-3">
          <label for="inputTitle" class="form-label text-primary"> <h1> Title </h1></label>
          <input type="text" class="form-control border border-primary" id="inputTitle" asp-for="title">
        </div>
        <div class="mb-3">
          <label for="inputDescription" class="form-label text-primary"><h1>Descrption</h1></label>
          <textarea class="form-control border border-primary" id="inputDescription" rows="10" asp-for="description"></textarea>
        </div>
                <button type="Submit" class="btn btn-lg btn-primary">Create Journal</button>
      </form>
</div>

Views/Journal/Index.cshtml
@model List<JourJournal.Models.Journal>
@{
    ViewData["Title"] = "Journal";
}
<div class="text-center mb-5">
    <h1 class="display-4 fw-semibold my-3"><a asp-controller="Journal" asp-action="Index">My Journal</a></h1>
    <!-- Button trigger modal -->
    <a class="btn btn-lg bg-primary text-white mx-auto" asp-controller="Journal" asp-action="AddJournal">Create New Journal</a>
</div>

<div class="container">
  <div class="row">
   @foreach (var journal in Model) {
     <div class="col-3 gap-5">
          <div class="card mb-3 border border-primary">
          <div class="card-header text-center bg-primary text-light py-2 fs-2">@journal.title</div>
          <div class="card-body ">
            <p class="card-text p-3">@journal.description</p>
          </div>
          <p class="d-none">ID: @journal.Id</p>
          <a class="btn btn-outline-primary px-5 mb-3 mx-auto" href="Journal/UpdateJournal/@journal.Id">View</a>
        </div>
      </div>
    }
  </div>
</div>

Views/Journal/UpdateJournal.cshtml
@model JourJournal.Models.UpdateJournalViewModel;

<div class="container w-50 my-5">
    <div class="text-center mb-5">
    <h1 class="display-4 fw-semibold my-3"><a asp-controller="Journal" asp-action="Index">My Journal</a></h1>
    <!-- Button trigger modal -->
    </div>
      <form method="post" action="UpdateJournal">
        <div class="mb-3">
          <label for="inputTitle" class="form-label d-none"> <h6> Id </h6></label>
          <input type="text" class="form-control d-none" id="inputTitle" asp-for="Id" readonly>
        </div>
         <div class="mb-3">
          <label for="inputTitle" class="form-label text-primary"> <h1> Title </h2></label>
          <input type="text" class="form-control" id="inputTitle" asp-for="title">
        </div>
        <div class="mb-3">
          <label for="inputDescription" class="form-label text-primary"><h1>Descrption</h1></label>
          <textarea class="form-control" id="inputDescription" rows="10" asp-for="description"></textarea>
        </div>
        <button type="Submit" class="btn btn-lg btn-success">Update Journal</button>
        <button type="Submit" class="btn btn btn-lg btn-danger" asp-action="DeleteJournal" asp-controller="Journal">Delete Journal</button>
      </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta Tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="title" content="JourJournal | Joshua Pautanes" />
    <meta
          name="description"
          content="Simple Journal Taking built in C#, .NET and Bootstrap"
        />
     <meta name="keywords" content="JourJournal, joshjoshuap, Joshua Pautanes" />
     <meta name="author" content="Joshua Pautanes" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

    <title>@ViewData["Title"] - JourJournal </title>

    <!-- Stylesheet -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JourJournal.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>